### ISSUE TITLE
Move from lein project to deps.edn

### ISSUE THREAD

**Issue by gigasquid** [cnuernber/libpython-clj#71] opened 2020-01-30 00:40 UTC
When working with `libpython-clj` from other projects or from journals like https://nextjournal.com/kommen/gigasquids-libpython-clj-examples, it's nice to be able to use a `:git/url` and `sha` to pin a specific commit - and not have to wait for a maven deployed version, (or have to clone the repo and install yourself.)

I'm happy to pitch in and look into converting to clojure deps and make it work with Circle CI if there is interest in this.

**Comment by jjtolton** [comment] 2020-01-30 01:05
Hi @gigasquid!  Would absolutely love this as well but as far as I know, `deps.edn` simply does not support the Java class building required for `libpython-clj`.  Since you brought it up I'll do a little bit more digging just to make sure I'm not crazy.

**Comment by jjtolton** [comment] 2020-01-30 01:14
https://clojurians.slack.com/archives/C6QH853H8/p1579876343024100
![image](https://user-images.githubusercontent.com/10394611/73411549-c93d6c80-42d3-11ea-9720-a7c305d13e91.png)

As of Jan 24th 2020 

Sorry!! I'd love to have this move to `deps.edn` too.  If this ever changes then happy to support that!  

Maybe we can find a different way to satisfy this requirement?  Some kind of installer script perhaps?

**Comment by gigasquid** [comment] 2020-01-30 02:00
I'll look into it and ask around for options and report back :)

**Comment by sanel** [comment] 2020-01-30 12:36
If I may suggest, why not keep both, or generate `deps.edn` from `project.clj`? Leiningen is pretty standard, more powerful and there is [plugin](https://github.com/reifyhealth/lein-git-down) for getting dependencies from git repos.

**Comment by jjtolton** [comment] 2020-01-30 14:48
@sanel that wouldn't be an issue and we'd be happy to maintain.  Only issue is that `deps.edn` can't build `libpython-clj` because of the Java class files.  So currently there's no really any point (that I know of) to a `deps.edn` file!

**Comment by gigasquid** [comment] 2020-01-30 21:20
There is a brand spanking new template out that looks like it handles javac for deps 🎉 
(ht to Alex Miller to pointing it out to me)

https://github.com/mikeananev/slib

In particular - here is the aliases to compile jars with javac and just javac alone, etc...

https://github.com/mikeananev/slib/blob/master/resources/clj/new/slib/deps.edn#L50

I haven't tried it myself yet, but if it looks like a good direction to you - I'd be happy to experiment with it in the project to see if it works.

**Comment by jjtolton** [comment] 2020-01-30 21:39
Sure!  And I'll do the same.  I think this may not solve the `:git/url` and `:sha` requirements but a move towards `deps.edn` is certainly something I'd be in support of.  It don't expect it would be much trouble maintaining both in parallel since there's the lein plugin for `deps.edn`.

**Comment by jjtolton** [comment] 2020-01-30 22:01
I can confirm that this does indeed compile `libpython-clj` successfully!  Just need a sign-off from @cnuernber on being okay to combine the plugin suggestion from @sanel with the toolset proposed by @gigasquid.  I still don't think this will allow for direct github pull downs but it could be accomplished with cloning and then running `clj -R:bg -A:javac` followed by REPL connection as normal (tested on Ubuntu/CIDER).

**Comment by cnuernber** [comment] 2020-01-30 22:06
I am curious as to whether it achieves the goal of the original post - Given this plugin, can you use use a `:git/url` and `sha` to pin a specific commit.  I use the lein deps plugin elsewhere and it works fine, for sure, but it adds a small layer of indirection and if we aren't concretely getting anything out of that layer I would rather avoid it.  On the other hand, if we can get benefit at all from moving to deps.edn + lein plugin I am down.

**Comment by gigasquid** [comment] 2020-01-30 22:27
There are *a lot* of other benefits from deps.edn. It is becoming a popular build tool for people to use generally, has a faster start up time for repls, and has more benefits ([see Rationale](https://github.com/clojure/tools.deps.alpha)) . I think the template shown, has all the same functionality that lein is currently providing:

(From the repo)

- build jar,
- compile java sources,
- create pom,
- sign jar file
- local install to .m2
- deploy jar to clojars
- run tests using kaocha

It would be possible to just switch from `lein` to clojure deps as the build tool and not have to maintain 2 dependency systems.

Happy to take some time to spike out a branch for you to check out with the changes. Just let me know.

**Comment by cnuernber** [comment] 2020-01-30 22:36
Well, then, Yes please :-).  Let's try it sounds worth it.

**Comment by gigasquid** [comment] 2020-01-30 22:37
Great - I'll dig in tomorrow and get a branch up for you to take a look at :)

**Comment by gigasquid** [comment] 2020-01-31 21:51
@cnuernber @jjtolton here is a WIP PR - please feel free to take it for a spin and feedback is most welcome 😸

**Comment by cnuernber** [comment] 2020-02-02 17:40
Closing this for now.  We will then need a build system on top of deps.edn and my current solution of using a project.clj that has the lein-deps plugin is clumsy.  We can slow-burn research on this over time as it isn't pressing.

**Closed by cnuernber** 2020-02-02 17:40 UTC
