### ISSUE TITLE
sandboxed dependency environments 

### ISSUE THREAD

**Issue by aaelony** [cnuernber/libpython-clj#70] opened 2020-01-29 22:25 UTC
A friend who uses python regularly indicated to me  
```
"When it comes to python, sandboxed dependency environments are a must."
```

To that end I am able to do something like: 
```
brew install pipenv
pipenv install seaborn
pipenv shell
python
``` 
then run the examples here: https://seaborn.pydata.org/introduction.html

However, the clojure `seaborn` example will error out for me at this line: https://github.com/gigasquid/libpython-clj-examples/blob/master/src/gigasquid/seaborn.clj#L17

with

```
gigasquid.seaborn=> gigasquid.seaborn=> (require-python '[seaborn :as sns])
:ok
gigasquid.seaborn=> (require-python '[matplotlib.pyplot :as pyplot])
:ok
gigasquid.seaborn=> (sns/set)
nil
gigasquid.seaborn=> (def dots (sns/load_dataset "dots"))
Execution error at libpython-clj.python.interpreter/check-error-throw (interpreter.clj:474).
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1392, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

```

Is there a way to make it use the correct python, i.e. the one in the `pipenv shell`?

Many thanks

**Comment by jjtolton** [comment] 2020-01-29 22:37
As of v1.33 you can do:

```clojure 
(py/initialize! :python-executable "/path/to/executable")
```
and
```clojure 
(py/initialize! :python-executable "/path/to/virtenv/bin/python")
```
I haven't tested this with pipenv yet.  Could you try this and let me know if it works?  If not I'll change this issue to "make py/initialize! work with pipenv", if that's alright with you :)  

Thank you!

**Comment by jjtolton** [comment] 2020-01-29 22:47
I should also point out that `py/initialize!` needs to be called BEFORE you `require` `[libpython-clj.require :refer [require-python]]`.  Typically what I do is I will make a separate file like this:

```clojure
(ns project.python 
  (:require [libpython-clj.python :as py]))

(py/initialize :python-executable "/path/to/my/env/bin/python")
```
and then in my main namespace
```clojure 
(ns project.core 
  (:require project.python 
            [libpython-clj.python :as py :refer [py. py.- py.. py* py**]] 
            [libpython-clj.require :refer [require-python import-python]]))


(do-fun-stuff!)
```

**Comment by aaelony** [comment] 2020-01-29 22:58
Within the `pipenv shell` it errors out earlier than the `py` namespace:

```

$ pipenv shell
Launching subshell in virtual environment…

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$  . /Users/aaelony/.local/share/virtualenvs/libpython-clj-examples-b-Zokxgy/bin/activate
(libpython-clj-examples) bash-3.2$ which python
/Users/aaelony/.local/share/virtualenvs/libpython-clj-examples-b-Zokxgy/bin/python
(libpython-clj-examples) bash-3.2$
(libpython-clj-examples) bash-3.2$ clj
Clojure 1.10.1
user=>

user=> (ns gigasquid.seaborn
  (:require [libpython-clj.require :refer [require-python]]
            [libpython-clj.python :as py :refer [py. py.. py.-]]
            [gigasquid.plot :as plot]))
Jan 29, 2020 2:56:47 PM clojure.tools.logging$eval498$fn__501 invoke
INFO: Executing python initialize with options:{:python-executable nil, :program-name nil, :python-home nil, :library-path nil}
Jan 29, 2020 2:56:47 PM clojure.tools.logging$eval498$fn__501 invoke
INFO: Detecting startup-info for Python executable:
Jan 29, 2020 2:56:47 PM clojure.tools.logging$eval498$fn__501 invoke
INFO: Startup info detected: {:python-home "/Users/aaelony/.local/share/virtualenvs/libpython-clj-examples-b-Zokxgy/bin/..", :lib-version "3.8", :libname "python3.8m", :java-library-path-addendum "/Users/aaelony/.local/share/virtualenvs/libpython-clj-examples-b-Zokxgy/bin/../lib"}
Jan 29, 2020 2:56:47 PM clojure.tools.logging$eval498$fn__501 invoke
INFO: Setting java library path: /Users/aaelony/.local/share/virtualenvs/libpython-clj-examples-b-Zokxgy/bin/../lib:/Users/aaelony/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
Jan 29, 2020 2:56:47 PM clojure.tools.logging$eval498$fn__501 invoke
INFO: Reference thread starting
Syntax error (ExceptionInfo) compiling at (libpython_clj/metadata.clj:13:1).
Failed to load library
gigasquid.seaborn=>
```

**Comment by aaelony** [comment] 2020-01-29 23:04
yeah - it fails early:

```

 $ pipenv shell
Launching subshell in virtual environment…

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$  . /Users/aaelony/.local/share/virtualenvs/libpython-clj-examples-b-Zokxgy/bin/activate
(libpython-clj-examples) bash-3.2$ which python
/Users/aaelony/.local/share/virtualenvs/libpython-clj-examples-b-Zokxgy/bin/python
(libpython-clj-examples) bash-3.2$ clj
Clojure 1.10.1

user=> (ns project.python
  (:require [libpython-clj.python :as py]))

nil

project.python=> (py/initialize! :python-executable
"/Users/aaelony/.local/share/virtualenvs/libpython-clj-examples-b-Zokxgy/bin/python")
Jan 29, 2020 3:02:41 PM clojure.tools.logging$eval492$fn__495 invoke
INFO: Executing python initialize with options:{:python-executable "/Users/aaelony/.local/share/virtualenvs/libpython-clj-examples-b-Zokxgy/bin/python", :program-name nil, :python-home nil, :library-path nil}
Jan 29, 2020 3:02:41 PM clojure.tools.logging$eval492$fn__495 invoke
INFO: Detecting startup-info for Python executable: /Users/aaelony/.local/share/virtualenvs/libpython-clj-examples-b-Zokxgy/bin/python
Jan 29, 2020 3:02:41 PM clojure.tools.logging$eval492$fn__495 invoke
INFO: Startup info detected: {:python-home "/Users/aaelony/.local/share/virtualenvs/libpython-clj-examples-b-Zokxgy/bin/..", :lib-version "3.8", :libname "python3.8m", :java-library-path-addendum "/Users/aaelony/.local/share/virtualenvs/libpython-clj-examples-b-Zokxgy/bin/../lib"}
Jan 29, 2020 3:02:41 PM clojure.tools.logging$eval492$fn__495 invoke
INFO: Setting java library path: /Users/aaelony/.local/share/virtualenvs/libpython-clj-examples-b-Zokxgy/bin/../lib:/Users/aaelony/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
Jan 29, 2020 3:02:41 PM clojure.tools.logging$eval492$fn__495 invoke
INFO: Reference thread starting
Execution error (ExceptionInfo) at tech.jna.base/do-load-library (base.clj:158).
Failed to load library
project.python=>

```

**Comment by jjtolton** [comment] 2020-01-29 23:15
Okay, thank you!  I'm attempting to reproduce the issue locally.

**Comment by aaelony** [comment] 2020-01-29 23:23
cool, thank-you!!

**Comment by jjtolton** [comment] 2020-01-29 23:29
Okay here's what I setup.

### setup
```bash
clj -A:new app pipenv.test
cd pipenv.test
python3.7 -m pipenv --python 3.7
python3.7 -m pipenv --venv # to get location of venv
python3.7 -m pipenv install seaborn
```

### deps.edn
```clojure 
{:paths ["resources" "src"]
 :deps  {org.clojure/clojure     {:mvn/version "RELEASE"}
         cnuernber/libpython-clj {:mvn/version "1.33"}}
 :aliases
 {:test {:extra-paths ["test"]
         :extra-deps  {org.clojure/test.check {:mvn/version "RELEASE"}
                       }}
  :runner
  {:extra-deps {com.cognitect/test-runner
                {:git/url "https://github.com/cognitect-labs/test-runner"
                 :sha     "76568540e7f40268ad2b646110f237a60295fa3c"}}
   :main-opts  ["-m" "cognitect.test-runner"
                "-d" "test"]}}}
```

### test.clj
#### this is where I import Python 
Use output of `python3.7 -m pipenv --venv` as location (plus `/bin/python`)
```clojure 
(ns pipenv.test
  (:require [libpython-clj.python :as py]))
(py/initialize! :python-executable "/home/jay/.local/share/virtualenvs/pipenv.test-Rx3tymi4/bin/python")
```
### Code
```clojure
(ns pipenv.core
  (:require
   pipenv.test
   [libpython-clj.python :as py :refer [py. py.- py.. py* py**]]
   [libpython-clj.require :refer [require-python import-python]]))


(require-python '[matplotlib.pyplot :as pyplot])

(comment
  (sns/set) 
  (def dots (sns/load_dataset "dots")))
```

This worked for me.  Try following these steps and see if the issue persists.

**Comment by jjtolton** [comment] 2020-01-29 23:33
Oh, I should also mention, don't use `pipenv shell`.  That's not necessary.  Might even break something.

**Comment by aaelony** [comment] 2020-01-30 00:03
getting closer...

I get:
```clojure
(ns pipenv.test
  (:require [libpython-clj.python :as py]
            [clojure.java.shell :only [sh]]))

(clojure.java.shell/sh "python3.7" "-m pipenv --venv") => {:exit 1, :out "", :err "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7: No module named  pipenv --venv\n"}

```

**Comment by aaelony** [comment] 2020-01-30 00:07
doing this first:

```
pip install seaborn



Creating a virtualenv for this project…
Pipfile: /Users/aaelony/aa/git/github/pipenv.test/Pipfile
Using /usr/local/Cellar/pipenv/2018.11.26_3/libexec/bin/python3.8 (3.8.1) to create virtualenv…
⠼ Creating virtual environment...Already using interpreter /usr/local/Cellar/pipenv/2018.11.26_3/libexec/bin/python3.8
Using real prefix '/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8'
New python executable in /Users/aaelony/.local/share/virtualenvs/pipenv.test-QmYINU7y/bin/python3.8
Also creating executable in /Users/aaelony/.local/share/virtualenvs/pipenv.test-QmYINU7y/bin/python
Installing setuptools, pip, wheel...
done.

✔ Successfully created virtual environment!
Virtualenv location: /Users/aaelony/.local/share/virtualenvs/pipenv.test-QmYINU7y
Creating a Pipfile for this project…
Installing seaborn…
Adding seaborn to Pipfile's [packages]…
✔ Installation Succeeded
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (fb2b7d)!
Installing dependencies from Pipfile.lock (fb2b7d)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 11/11 — 00:00:02
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

**Comment by jjtolton** [comment] 2020-01-30 00:07
If you're going that route make sure to split on whitespace in `clojure.java.shell/sh`.  Check the example: https://clojuredocs.org/clojure.java.shell/sh#example-542692d6c026201cdc3270ea

You could also do it the stone age way and and just copy/paste from the shell! :P

**Comment by jjtolton** [comment] 2020-01-30 00:08
`(clojure.java.shell/sh "python3.7" "-m"  "pipenv"  "--venv")`

**Comment by aaelony** [comment] 2020-01-30 01:56
from the shell I get the same thing:

```
 $ python3.7 -m pipenv --venv
/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7: No module named pipenv
```

**Comment by jjtolton** [comment] 2020-01-30 01:59
Try `pipenv --venv` instead

**Comment by aaelony** [comment] 2020-01-30 02:34
```
pipenv --venv
``` 
works!

or 

```clojure

(ns pipenv.test
  (:require [libpython-clj.python :as py]
            [clojure.java.shell :only [sh]]
            [clojure.string :as str]))

(def venv (-> "pipenv" (clojure.java.shell/sh "--venv") :out str/trim-newline))
venv

```


Unfortunately though:
```clojure

(py/initialize! :python-executable venv)

```

gives 
```

 Show: Project-Only All
  Hide: Clojure Java REPL Tooling Duplicates  (11 frames hidden)

2. Unhandled java.io.IOException

1. Caused by java.io.IOException
   error=13, Permission denied

          ProcessImpl.java:   -2  java.lang.ProcessImpl/forkAndExec
          ProcessImpl.java:  340  java.lang.ProcessImpl/<init>
          ProcessImpl.java:  271  java.lang.ProcessImpl/start
       ProcessBuilder.java: 1107  java.lang.ProcessBuilder/start
              Runtime.java:  591  java.lang.Runtime/exec
                 shell.clj:  113  clojure.java.shell/sh
                 shell.clj:   79  clojure.java.shell/sh
               RestFn.java:  436  clojure.lang.RestFn/invoke
           interpreter.clj:   31  libpython-clj.python.interpreter/python-system-data
           interpreter.clj:   29  libpython-clj.python.interpreter/python-system-data
           interpreter.clj:   75  libpython-clj.python.interpreter/python-system-info
           interpreter.clj:   43  libpython-clj.python.interpreter/python-system-info
           interpreter.clj:  151  libpython-clj.python.interpreter/detect-startup-info
           interpreter.clj:  145  libpython-clj.python.interpreter/detect-startup-info
           interpreter.clj:  416  libpython-clj.python.interpreter/initialize!
           interpreter.clj:  408  libpython-clj.python.interpreter/initialize!
               RestFn.java:  619  clojure.lang.RestFn/invoke
                python.clj:  242  libpython-clj.python/initialize!
                python.clj:  229  libpython-clj.python/initialize!
               RestFn.java:  421  clojure.lang.RestFn/invoke
                      REPL:   11  pipenv.test/eval34938
                  core.clj: 3214  clojure.core/eval
                  core.clj: 3210  clojure.core/eval
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  368  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
                  AFn.java:   22  clojure.lang.AFn/run
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  834  java.lang.Thread/run
```

Unclear how to unlock... perhaps chmod ?

**Comment by jjtolton** [comment] 2020-01-30 02:35
try
```clojure 
(def venv (-> "pipenv" (clojure.java.shell/sh "--venv") :out str/trim-newline (str "/bin/python"))
```

**Comment by aaelony** [comment] 2020-01-30 02:36
same error :(

**Comment by jjtolton** [comment] 2020-01-30 02:38
what's the value of `venv` after you do that?

**Comment by jjtolton** [comment] 2020-01-30 02:40
Tell you what, can you head over to https://clojurians.zulipchat.com/#narrow/stream/215609-libpython-clj-dev/topic/help-wanted ?  Might be able to help you a little better there.

**Comment by aaelony** [comment] 2020-01-30 02:41
there was a closing ")" missing..

on my system, I need to invoke `python3`.  Unfortunately, /usr/bin/python is python 2.7.

```clojure
(def venv (-> "pipenv" (clojure.java.shell/sh "--venv") :out str/trim-newline (str "/bin/python3")))
;; venv => "/Users/aaelony/.local/share/virtualenvs/pipenv.test-QmYINU7y/bin/python3"


```

1. Unhandled clojure.lang.ExceptionInfo
   Failed to load library
   {:libname "python3.6m",
    :paths
    [[:system ["python3.6m"]]
     [:java-library-path
      ["/Users/aaelony/.local/share/virtualenvs/pipenv.test-QmYINU7y/bin/../lib/libpython3.6m.dylib"
       "/Users/aaelony/Library/Java/Extensions/libpython3.6m.dylib"
       "/Library/Java/Extensions/libpython3.6m.dylib"
       "/Network/Library/Java/Extensions/libpython3.6m.dylib"
       "/System/Library/Java/Extensions/libpython3.6m.dylib"
       "/usr/lib/java/libpython3.6m.dylib"
       "./libpython3.6m.dylib"]]]}
                  base.clj:  158  tech.jna.base/do-load-library
                  base.clj:  123  tech.jna.base/do-load-library
                  base.clj:  178  tech.jna.base/load-library
                  base.clj:  174  tech.jna.base/load-library
                   jna.clj:   87  tech.jna/load-library
                   jna.clj:   85  tech.jna/load-library
           interpreter.clj:  404  libpython-clj.python.interpreter/setup-direct-mapping!
           interpreter.clj:  402  libpython-clj.python.interpreter/setup-direct-mapping!
           interpreter.clj:  441  libpython-clj.python.interpreter/initialize!
           interpreter.clj:  408  libpython-clj.python.interpreter/initialize!
               RestFn.java:  619  clojure.lang.RestFn/invoke
                python.clj:  242  libpython-clj.python/initialize!
                python.clj:  229  libpython-clj.python/initialize!
               RestFn.java:  421  clojure.lang.RestFn/invoke
                      REPL:   21  pipenv.test/eval34964
                  core.clj: 3214  clojure.core/eval
                  core.clj: 3210  clojure.core/eval
                  main.clj:  437  clojure.main/repl/read-eval-print/fn
                  main.clj:  458  clojure.main/repl/fn
                  main.clj:  368  clojure.main/repl
               RestFn.java: 1523  clojure.lang.RestFn/invoke
                  AFn.java:   22  clojure.lang.AFn/run
                  AFn.java:   22  clojure.lang.AFn/run
               Thread.java:  834  java.lang.Thread/run

```

**Comment by jjtolton** [comment] 2020-01-30 02:47
so from a fresh REPL

```clojure 
user=> (require '[libpython-clj.python :as py])
nil
user=> (py/initialize! :python-executable "/Users/aaelony/.local/share/virtualenvs/pipenv.test-QmYINU7y/bin/python3")
```
Give that a shot and see if it works

**Comment by cnuernber** [comment] 2020-01-30 14:58
https://github.com/cnuernber/libpython-clj/issues/61#issuecomment-577996040

We need the shared library produced when you install the virtual env.  

Really what we need is an environments.md file under docs that describes that issue and this one and the fix (if Stuart's fix works for you).

**Comment by aaelony** [comment] 2020-01-30 16:14
Not working just yet... getting `Failed to load library` as error.

**Comment by cnuernber** [comment] 2020-01-30 16:18
Did you try with the suggested env variable when installing the env?

>> env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.6.9

Specifically, where is the python3.6m shared library on your system if you search?

**Comment by aaelony** [comment] 2020-01-30 16:45
I think that is the issue. I need to set the  env variable correctly.  My system is literally litered with such libs.

```


/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/libpython3.7m.dylib
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/libpython3.7m.dylib
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/libpython3.7m.dylib
/Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/libpython3.7m.dylib
/System/Volumes/Data/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
/System/Volumes/Data/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/libpython3.7m.dylib
/System/Volumes/Data/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/libpython3.7m.dylib
/System/Volumes/Data/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/libpython3.7m.dylib
/System/Volumes/Data/Library/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
/System/Volumes/Data/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin/libpython3.7m.dylib
/System/Volumes/Data/Users/aaelony/python/miniconda3/pkgs/python-3.7.4-h359304d_1/lib/libpython3.7m.dylib
/System/Volumes/Data/Users/aaelony/python/miniconda3/lib/libpython3.7m.dylib
/Users/aaelony/python/miniconda3/pkgs/python-3.7.4-h359304d_1/lib/libpython3.7m.dylib
/Users/aaelony/python/miniconda3/lib/libpython3.7m.dylib
```

Unfamiliar with a good way to housekeep, hence the need for sandboxing.

**Comment by cnuernber** [comment] 2020-01-30 17:27
This is why I recommend using docker.  We have a clear example of how to use docker including mounting your local project [here](https://github.com/cnuernber/facial-rec).  Essentially docker is the most sandboxed you can get :-).

**Comment by aaelony** [comment] 2020-01-30 18:05
Totally.  I'll look into the facial-rec example you provided.

**Comment by jjtolton** [comment] 2020-01-30 18:24
I'm trying to determine if `py/initialize!` is what is crashing or if the `require-python` is causing the issue. I'm not sure where the `Failed to load library` message is coming from -- I don't think that originates directly from `libpython-clj`.

Also I wonder if this is a Mac specific issue or there's just some local environment stuff going on.  I managed to get pipenv working on Ubuntu.  If I get some time I'll test on a Mac and see if it comes up there.

**Comment by aaelony** [comment] 2020-01-30 19:13
Here is the current state of progress:

```clojure


$ clj
Clojure 1.10.1
(ns pipenv.test
  (:require [libpython-clj.python :as py]
            [clojure.java.shell :only [sh]]
            [clojure.string :as str]))

nil
pipenv.test=> 
pipenv.test=> (def venv (-> "pipenv" (clojure.java.shell/sh "--venv") :out str/trim-newline (str "/bin/python3")))
#'pipenv.test/venv
pipenv.test=>
pipenv.test=> venv
"/Users/aaelony/.local/share/virtualenvs/pipenv.test-QmYINU7y/bin/python3"
pipenv.test=> (py/initialize! :python-executable venv)
Jan 30, 2020 11:03:15 AM clojure.tools.logging$eval492$fn__495 invoke
INFO: Executing python initialize with options:{:python-executable "/Users/aaelony/.local/share/virtualenvs/pipenv.test-QmYINU7y/bin/python3", :program-name nil, :python-home nil, :library-path nil}
Jan 30, 2020 11:03:15 AM clojure.tools.logging$eval492$fn__495 invoke
INFO: Detecting startup-info for Python executable: /Users/aaelony/.local/share/virtualenvs/pipenv.test-QmYINU7y/bin/python3
Jan 30, 2020 11:03:16 AM clojure.tools.logging$eval492$fn__495 invoke
INFO: Startup info detected: {:python-home "/Users/aaelony/.local/share/virtualenvs/pipenv.test-QmYINU7y/bin/..", :lib-version "3.8", :libname "python3.8m", :java-library-path-addendum "/Users/aaelony/.local/share/virtualenvs/pipenv.test-QmYINU7y/bin/../lib"}
Jan 30, 2020 11:03:16 AM clojure.tools.logging$eval492$fn__495 invoke
INFO: Setting java library path: /Users/aaelony/.local/share/virtualenvs/pipenv.test-QmYINU7y/bin/../lib:/Users/aaelony/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
Jan 30, 2020 11:03:16 AM clojure.tools.logging$eval492$fn__495 invoke
INFO: Reference thread starting
Execution error (ExceptionInfo) at tech.jna.base/do-load-library (base.clj:158).
Failed to load library

```

**Comment by jjtolton** [comment] 2020-01-30 21:45
I haven't tested on Python 3.8 yet.  I'll see if I can give that a shot.

**Comment by cnuernber** [comment] 2020-01-30 22:09
@aaelony  - does `libpython3.8m.dylib` exist at `:java-library-path-addendum "/Users/aaelony/.local/share/virtualenvs/pipenv.test-QmYINU7y/bin/../lib"`?

If not, then my question is was the env installed with 
```console
env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.8
```
The system things that the python shared library is installed at the above location.

**Comment by gigasquid** [comment] 2020-01-31 00:52
That was my thought too @aaelony  - it kinda looks like this issue https://github.com/cnuernber/libpython-clj/issues/61

**Comment by jjtolton** [comment] 2020-02-03 19:18
@cnuernber recommend closing.  Tested that pipenv works for Ubuntu (see details above).  If it doesn't work for Mac that would be a separate issue.  @aaelony if you're continuing to experience problems please visit out help-wanted topic and we'll continue to assist until you get it!

**Closed** 2020-02-03 20:36 UTC
